import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PT_Serif } from "next/font/google";

const PTSerif400 = PT_Serif({
  weight: "400",
  subsets: ["latin"],
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en" className={PTSerif400.className}>
      <body>
        <header className="text-[4rem] h-60 bg-white flex relative">
          <h1 className="left-[4rem] bottom-[2rem] absolute">Portfolio Page</h1>
        </header>
        {props.children}
      </body>
    </html>
  );
}
